### ISSUE TITLE
Redirect www.onodo.org to onodo.org

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/onodo#326]

**Comment by esebastian** [comment]
At the moment the redirect is managed at the DNS provider level, and it works fine on HTTP but not in HTTPS (i.e. it redirects http://www.onodo.org but not https://www.onodo.org).

In order to make it work, we'll need to manage the redirection in our web server; I'll take care of that if there are no concerns about it.

**Comment by esebastian** [comment]
The configuration is ready. Once the Nginx server is restarted, the users accessing through www.onodo.org will need to login again, as the session cookie for one host is not shared with the other.

It could be a good idea to coordinate with the deployment of #348, to avoid more than one forced logout.
