### ISSUE TITLE
Network Analysis not rerunning

### ISSUE THREAD

**Issue by wpkurtz** [civio/onodo#363]
Hello,

We're using Onodo for one of my classes, and a student is having a problem with the network analysis for his graph. When he attempts to rerun the analysis, the system won't recalculate. He has cleared his cache and logged out/in to try and remedy the issue. This enabled him to recalculate but did not give him any new values. 

Do you have any suggestions? Is there a way for him to delete the analysis values and run them fresh? We tried downloading the data, removing the columns with the analysis statistics, and creating a new network. This worked, but none of the images he had associated with his nodes carried over.

Thanks for any guidance you could lend.

Best,

Wendy

**Comment by dcabo** [comment]
Hi, Wendy. Sorry to hear about the issues you're having. :/

We haven't been able to maintain Onodo properly for a while (we're a small non-profit and Onodo is a side-project), so I'm not sure we'll be able to reproduce and fix the issue properly in the short-term. Maybe we can delete the analysis results manually (thinking out loud), I don't know. Which graph is it exactly? (@esebastian, do you remember how this part of the app worked?)

**Comment by wpkurtz** [comment]
Hello and thank you so much for your timely response! Here's a link to the published network: https://onodo.org/visualizations/144512. 

This is such a great tool for teaching about network graphs, so I'm sorry to hear it's not being actively maintained! But I completely understand. Thank you for sharing that information.

**Comment by dcabo** [comment]
Hi, Wendy, sorry for the delay: it's been a while since I touched any of this, so took some time to get into it again.

I did find the cause of the problem, there's a problem with the way the code doing the calculations. The bad news are that it's going to take me a bit to fix it properly (#363), because I need to make sure I don't break anything else while fixing it. But good news are that there's a simple workaround (which worked for me): the code is choking when dealing with incomplete links, i.e. ones without a source, target or both; if you go to the Links tab and delete those that are incomplete you should be able to re-run the calculations successfully.

Sorry for the inconvenience and the delay!

**Comment by dcabo** [comment]
@wpkurtz I fixed the issue with incomplete relations making the network analysis fail. Sorry about that. Please let me know if you run into further problems.
